config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  get 'generate', to: 'pages#generate'
  resources :projects, only: [:index, :show, :create, :new, :destroy, :update] do
    resources :files, only: [:index]
    get 'template', to: 'projects#template'
    get 'template/:all_params', to: 'projects#template_params'
  end

  get 'about', to: 'pages#about'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% unless controller_name == "sessions" && action_name == "new" %>
  <div class="footer border-top">
    <div class="footer-links">
      <a href="#" class="a1"><i class="fab fa-github"></i></a>
      <a href="mailto:waldevelopers@gmail.com"  class="a2"><i class="fas fa-envelope"></i></a>
      <a href="mailto:waldevelopers@gmail.com" class="a3" ><strong>Hire Us</strong></a>
    </div>

    <div class="footer-copyright">
     <i class="far fa-copyright"></i> WALD, 2019
    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-flex navbar navbar-expand-sm navbar-light navbar-lewagon <%= controller_name == 'pages' && action_name == 'home' ? 'navbar-transparent' : '' %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'WALD_Oficial_Logo.png', id: "logo_wald" %>
  <% end %>
  <div class="align-self-center" id="wald-text" style='<%= controller_name == "pages" && action_name == "home" ? "" : "display: none;" %>' >  We Are Lazy Developers </div>
  <div class="flex-grow-1"></div>
<!--   <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> -->


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>

      <div class="d-flex align-items-center in-nav-link-div">
        <li class="nav-item in-nav-link hvr-float-shadow">
          <%= link_to "New Project", new_project_path, class: "nav-item" %>
        </li>
        <li class="nav-item in-nav-link hvr-float-shadow">
          <%= link_to "Projects", projects_path, class: "nav-item" %>
        </li>
      </div>

        <li class="nav-item dropdown">
          <%= image_tag current_user.avatar, class: "avatar dropdown-toggle avatar-size-navbar", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "About us", about_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <!-- <li class="align-self-center flex-grow-1" id="wald-text">  We Are Lazy Developers </li> -->
        <li id="navbar-login-button" class="nav-item" style ="text-color: white;">
          <%= link_to "Sign in with", user_github_omniauth_authorize_path, method: :post, style: "color: white;" %> <i class="fab fa-github" style="color: white;"></i><br />
        </li>
      <% end %>
    </ul>
  </div>
</div>