config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users, :controllers => { omniauth_callbacks: 'callbacks' }

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  get 'generate', to: 'pages#generate'
  resources :projects, only: [:index, :show, :create, :new, :destroy, :update] do
    resources :files, only: [:index]
    get 'template', to: 'projects#template'
    get 'template/:all_params', to: 'projects#template_params'
  end

  get 'about', to: 'pages#about'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :commands, dependent: :destroy

  validates :name, presence: true
  validates :xml_schema, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :destroy, :update]
  # before_action :check_if_user_is_owner?,  only: [:show]
  skip_before_action :authenticate_user!, only: [:template, :template_params, :devise_template, :devise_template_params, :show]

  def index
    @projects = Project.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @project = Project.new
    @project.user = current_user
  end

  def create
    @project = Project.new(project_params)
    parse_xml(params[:project][:xml_schema])
    @project.tables = @tables_arr
    @project.models = model_names(@tables_arr)
    @project.user = current_user
    if @project.save
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  def show
    @project.user = current_user
    xml_string = @project.xml_schema
    parse_xml(xml_string)
  end

  def destroy
    @project.user = current_user

    @project.destroy

    respond_to do |format|
      format.js
    end
  end

  def update
    @project.update(project_params)

    redirect_to project_path(@project)
  end


  def template
    @project = Project.find(params[:project_id])
    xml_string = @project.xml_schema
    parse_xml(xml_string)
    send_data templating(@commands), filename: "template-#{@project.name.gsub(/\s+/m, '-').downcase}.rb", disposition: 'attachment'
  end

  def template_params
    @project = Project.find(params[:project_id])
    xml_string = @project.xml_schema
    check_devise(params[:all_params])
    check_github(params[:all_params])
    check_heroku(params[:all_params])
    check_scaffold(params[:all_params])
    check_seed(params[:all_params])
    if @devise == true
      @devise_model = "user"
      devise_parse_xml(xml_string)
      send_data devise_templating(@commands), filename: "template-#{@project.name.gsub(/\s+/m, '-').downcase}.rb", disposition: 'attachment'
    else
      parse_xml(xml_string)
      send_data templating(@commands), filename: "template-#{@project.name.gsub(/\s+/m, '-').downcase}.rb", disposition: 'attachment'
    end
  end

  private

  ##########################################
  # basic controller methods :
  ##########################################

  def project_params
    params.require(:project).permit(:name, :user_id, :xml_schema)
  end

  def check_if_user_is_owner?
    current_user.id == @project.user_id
  end

  def set_project
    @project = Project.find(params[:id])
  end

  ##########################################
  # parsing XML methods :
  ##########################################

  def parse_xml(xml_string)
    doc = Nokogiri::XML(xml_string)

    tables_arr = []
    @show_tables_arr = []
    doc.root.search('table').each do |table|
      # find primary key
      primary_row_name = table.search('key/part').text
      columns_arr = []

      table.search('row').each do |row|
        column_name = row.attribute('name').value
        data_type = row.search('datatype').text
        relations = row.search('relation')
        relations_arr = []
        sorting_relations_arr = []
        fk = relations.count > 0
        pk = column_name == primary_row_name

        relations.each do |relation|
          relation_table = relation.attribute('table').value
          relation_row = relation.attribute('row').value
          relation_hash = {
            relation_table: relation_table,
            relation_row: relation_row
          }
          relations_arr << relation_hash
          sorting_relations_arr << relation_hash
        end

        columns_arr << {
          column_name: column_name,
          data_type: to_data_type(data_type),
          relations: relations_arr,
          pk: pk,
          fk: fk,
          # for sorting
          sorting_relations: sorting_relations_arr
        }
      end

      tables_arr << {
        table_name: table.attribute("name").value,
        columns: columns_arr
      }
    end

    @tables_arr = order(tables_arr)
    @commands = commands
    @rails_commands = rails_commands
  end

  def model_names(tables)
    model_names = []

    tables.each do |table|
      # if table[:table_name].length <= 1
      #   model_names << "#{table[:table_name]}".gsub(/\s+/m, '_').downcase
      # elsif table[:table_name].chars.last(3).join == "ies"
      #   model_names << "#{table[:table_name][0..-4]}y".gsub(/\s+/m, '_').downcase
      # elsif table[:table_name].chars.last == "s"
      #   model_names << "#{table[:table_name][0..-2]}".gsub(/\s+/m, '_').downcase
      # else
      #   model_names << "#{table[:table_name]}".gsub(/\s+/m, '_').downcase
      # end

      model_names << "#{table[:table_name].singularize}".gsub(/\s+/m, '_').downcase
    end

    model_names
  end

  def to_data_type(schema_data_type)
    case schema_data_type.downcase
    when "integer", "tinyint", "smallint", "mediumint", "int", "bigint", "single precision", "double precision"
      :integer
    when "decimal"
      :decimal
    when "char", "varchar", "varbinary"
      :string
    when "text"
      :text
    when "binary", "bit"
      :binary
    when "boolean"
      :boolean
    when "date", "year"
      :date
    when "time"
      :time
    when "timestamp", "timestamp w/ tz", "timestamp wo/ tz"
      :timestamp
    when "datetime"
      :datetime
    end
  end

  def order(tables_arr)
    sorting_tables_arr = tables_arr
    ordered_tables_arr = []

    return_and_remove_fks(sorting_tables_arr, ordered_tables_arr)
  end

  def return_and_remove_fks(sorting_tables_arr, ordered_tables_arr)
    # if statement to stop infinate recurrsion
    if sorting_tables_arr.any?
      # check tables for no fks & set sorting_fk
      sorting_tables_arr.each do |table|
        no_fks_array = []
        table[:columns].each do |column|
          no_fks_array << column[:sorting_relations].empty?
        end
        # push table to ordered_tables_arr if no_fks, and remove it from sorting_table_arr
        unless no_fks_array.include?(false)
          ordered_tables_arr << table
          sorting_tables_arr.delete(table)
        end
      end

      # remove now sorted table from other tables sorting_relations
      ordered_tables_arr.each do |ord_table|
        # for every ordered table, go through the remaining tables
        sorting_tables_arr.each do |table|
          table[:columns].each do |column|
            column[:sorting_relations].each do |relation|
              # remove any relation from sorting_relations which has been sorted already
              if relation[:relation_table] == ord_table[:table_name]
                column[:sorting_relations].delete(relation)
              end # if
            end # relations loop
          end # column loop
        end # remaining tables loop
      end # already ordered tables loop
    else
      return ordered_tables_arr
    end
    return_and_remove_fks(sorting_tables_arr, ordered_tables_arr)
  end


  ##########################################
  # creating the commands methods :
  ##########################################

  def commands
    @commands = []

    @tables_arr.each do |table|
      table_name = table[:table_name].singularize.gsub(/\s+/m, '_').downcase

      # if table_name.length <= 1
      #   command = "rails g model #{table_name} "
      # elsif table_name.chars.last(3).join == "ies"
      #   command = "rails g model #{table_name[0..-4]}y "
      # elsif table_name.chars.last == "s"
      #   command = "rails g model #{table_name[0..-2]} "
      # else
      #   command = "rails g model #{table_name} "
      # end

      command = "rails g model #{table_name} "

      table[:columns].each do |column|
        next if column[:column_name] == "id"

        column_name = column[:column_name]
        data_type = column[:data_type]

        command += " #{column_name}:#{data_type}"

        if column[:fk] == true
          column[:relations].each do |relation|
            relation_table_name = relation[:relation_table].singularize.gsub(/\s+/m, '_').downcase

            # if relation_table_name.length <= 1
            #   command += " #{relation_table_name}:references"
            # elsif relation_table_name.chars.last(3).join == "ies"
            #   command += " #{relation_table_name[0..-4]}y:references"
            # elsif relation_table_name.chars.last == "s"
            #   command += " #{relation_table_name[0..-2]}:references"
            # else
            #   command += " #{relation_table_name}:references"
            # end

            command += " #{relation_table_name}:references"

          end
        end
      end

      splitted_commands = command.split(" ").map do |cmd|
        cmd.include?("id") ? cmd = "" : cmd + " "
      end
      @commands << splitted_commands.join("")
    end
    @commands
  end


  def rails_commands

    @rails_commands = []

    @tables_arr.each do |table|
      singular_table_name = table[:table_name].singularize.gsub(/\s+/m, '_').downcase

      # if table_name.length <= 1
      #   singular_table_name = "#{table_name}"
      # elsif table_name.chars.last(3).join == "ies"
      #   singular_table_name = "#{table_name[0..-4]}y"
      # elsif table_name.chars.last == "s"
      #   singular_table_name = "#{table_name[0..-2]}"
      # else
      #   singular_table_name = "#{table_name}"
      # end

      if @scaffold_models.present?
        if @scaffold_models.include?(singular_table_name)
          command = "scaffold #{singular_table_name} "
        else
          command = "model #{singular_table_name} "
        end
      else
        command = "model #{singular_table_name} "
      end

      table[:columns].each do |column|
        next if column[:column_name] == "id"

        column_name = column[:column_name]
        data_type = column[:data_type]

        command += " #{column_name}:#{data_type}"

        if column[:fk] == true
          column[:relations].each do |relation|

app/views/projects/_form.html.erb
<%= simple_form_for [@user, @project] do |f| %>
  <div class="form-inputs">
    <%= f.input :name, label: 'Your project name', error: 'Project Name is mandatory, please specify one', placeholder: 'Cool name here' %>
    <%= f.input :xml_schema, input_html: { id: "box-to-paste" }, label: 'Paste your XML schema code here', error: 'You must paste XML code to convert', placeholder: '<table x="252" y="109" name="files">
<row name="id" null="1" autoincrement="1">
  <datatype>TINYINT</datatype>
  <default>NULL</default>
</row>
<row name="artist_id" null="1" autoincrement="0">
  <datatype>TINYINT</datatype>
  <default>NULL</default>
  <relation table="artists" row="id" />
</row>' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn convert-now-button hvr-grow" %>
  </div>
<% end %>

app/views/projects/_projects.html.erb
<% @projects.each do |project| %>
  <p class="project-result" data-project-class="<%= project.id %>" id="project-<%= project.id %>" >
    <span class="searchable-area" data-target="project-<%= project.id %>">
      <span data-test="<%= project.name.gsub(/\s+/m, '_').downcase %>-<%= project.id %>">
      <%= link_to project.name.gsub(/\s+/m, '_').downcase, project_path(project) %>
      </span>
      <span class="models-grey-text"><span></span>
        <% project.models.each_with_index do |model, i| %>
          <span data-test="<%= model %>-<%= project.id %>">
            <%= " #{model}" %>
          </span>
          <%="#{ i+1 < project.models.length ? "," : "" }" %>
        <% end %>
      </span>
    </span>
    <span class="date-grey-text"><%= project.created_at.strftime("%m/%d/%Y %I:%M%p") %></span>

    <%= link_to project_path(project), class: "delete-icon", remote: true do %>
      <i class="far fa-trash-alt"></i>
    <% end %>

  </p>

<% end %>

app/views/projects/destroy.js.erb
document.querySelector("[data-project-class='<%= @project.id %>']").remove();

app/views/projects/index.html.erb
<div class="container" style="min-height: 100vh">
<h1>Your Projects</h1>
<div class="border-bottom my-4"></div>

<div class="light-grey-area">
  <p id="test">
    <strong>Search</strong> for project or model names
  </p>
  <input type="text" class="form-control index-search-box" id="index-search-box">
</div>

  <%= render 'projects', projects: @projects %>

</div>
<!-- here we will add a list of all file for each project -->

app/views/projects/new.html.erb
<div class="container" style=" font-family: Roboto, sans-serif;">
  <div class="typewriter">
    <h1 class="d-flex justify-content-center my-2" style="margin-bottom: 45px;">Your new Rails project</h1>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-sm-12 col-md-8">
      <div class="border-bottom my-5"></div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">

  <h1><%= @project.name.gsub(/\s+/m, '_').downcase %></h1>

<div class="border-bottom my-4"></div>
<div class="row">
<div class="col-md-6">
  <p>Edit text by clicking on it.</p>
  <p>Click  <i class="fas fa-copy"></i>  to copy a command.</p>
  <p>Run commands in your terminal.</p>
</div>

<div class="col-md-6 text-right">
  <div class="share-link-desktop">
    <!-- <p><strong>Share this page</strong></p> -->
    <div class="link-code-block" style="float: right; min-width: 380px;">
      <div class="code-row">
        <div class="code-copy-icon"><i class="fas fa-copy" data-target="code-input-link"></i></div>
        <!-- <input class="link-code-input" type="text" id="code-input-link" value="<%= request.original_url %>" spellcheck="false"> -->
        <strong style="margin-top: 2px;">Share&nbsp</strong>
        <input class="link-code-input" type="text" id="code-input-link" value="<%= request.original_url %>" spellcheck="false" style="width:<%= request.original_url.length * 9 %>px">
        <!-- <span class="link-code-input" type="text" id="code-input-link" value="<%= request.original_url %>" spellcheck="false" contenteditable="true"><%= request.original_url %></span> -->
      </div>
    </div>
  </div>
</div>
</div>
<div class="mb-4 mt-2 border-bottom"></div>



<div class="d-flex">
  <p><strong>Create a Rails project</strong></p>
  <div class="flex-grow-1"></div>
    <button class="align-items-center pulsate-bck" data-toggle="modal" data-target="#exampleModalCenter">Understand your template</button>
  </div>


<p>This command generates a new Rails project in a directory named '<%= @project.name.gsub(/\s+/m, '_').downcase %>'. </p>


<div class="code-block-commands">
  <div class="code-row">
    <div class="code-copy-icon"><i class="fas fa-copy" data-target="code-input-command"></i></div>
    <textarea class="code-input" rows="6" cols="50" id="code-input-command" spellcheck="false">
rails new \
  --database postgresql \
  --webpack \
  -m <%= project_template_url(@project) %> \
  <%= @project.name.gsub(/\s+/m, '_').downcase %>
    </textarea>
  </div>
</div>


<p>
  <strong>
    Customise
  </strong>
</p>


<div class="customise-options-div">

    <div class="d-flex template-option-div">
     <span class="template-option-span">Create repository on <strong>Github</strong>?</span>
       <div class="github-checkbox show-page-checkbox">
         <input data-target="&github" type="checkbox" class="form-check-input wald-checkbox" id="github_checkbox">
       </div>
    </div>

     <div class="d-flex template-option-div">
       <span class="template-option-span">Deploy to <strong>Heroku</strong>?</span>
         <div class="heroku-checkbox show-page-checkbox">
           <input data-target="&heroku" type="checkbox" class="form-check-input wald-checkbox" id="heroku_checkbox">
         </div>
        <span class="devise-for-span devise-hidden" id="heroku_show_hide_span">
         <span>
         You must be logged-in to Heroku
         </span>
        </span>
      </div>

      <div class="d-flex template-option-div">
       <span class="template-option-span"><strong>Seed</strong> your models?</span>
         <div class="seed-checkbox show-page-checkbox">
           <input data-target="&seed" type="checkbox" class="form-check-input wald-checkbox" id="seed_checkbox">
         </div>
      </div>

  <div class="d-flex template-option-div">
    <span class="template-option-span"><strong>Devise</strong> for user model?</span>
      <div class="devise-checkbox show-page-checkbox">
        <input type="checkbox" data-target="&devise" class="form-check-input wald-checkbox" id="devise_checkbox">
      </div>
      <span class="d-flex devise-hidden" id="devise_show_hide_span">
        <span class="devise-for-span">
          <% if @project.models.include?("user") %>
            Devise will be applied to your 'user' model.
          <% else %>
            <span style="color: rgb(255, 95, 63)">You do not have a 'user' model.</span> A user model will be created for you if you select devise.
          <% end %>
        </span>
      </span>
   </div>


  <span class="scaffold-title-template-option-span"><span class="scaffold-span"><strong>Scaffold</strong> your models?</span></span>
  <div class="d-flex flex-wrap scaffold-template-option-div">
    <!-- <span class="scaffold-title-template-option-span"><span class="scaffold-span"><strong>Scaffold</strong> your models?</span></span> -->


    <div class="scaffold-checkbox-div" data-color="&s-all">
      <div class="heroku-checkbox show-page-checkbox">
        <input data-target="&s-all" type="checkbox" class="form-check-input wald-checkbox in-div-wald-checkbox" id="s-all">
      </div>
      <span class="scaffold-template-option-span">all</span>
    </div>
    <% @project.models.each do |model| %>
    <div class="scaffold-checkbox-div" data-color="&s-<%= model %>">
      <div class="heroku-checkbox show-page-checkbox">
        <input data-target="&s-<%= model %>" type="checkbox" class="form-check-input wald-checkbox in-div-wald-checkbox scaffold-checkbox" id="s-<%= model %>">
      </div>
      <span class="scaffold-template-option-span"><%= model %></span>
    </div>
    <% end %>
  </div>



</div>

<div class="my-4 border-bottom"></div>

  <p><strong>Your commands to generate models.</strong></p>
  <p>These commands are already in your template and will run automatically.</p>
  <p>If you don't want to use the template, you can run these commands individually.</p>
  <div class="code-block">
    <% @commands.each_with_index do |command, index| %>
      <div class="code-row">
        <div class="code-copy-icon"><i class="fas fa-copy" data-target="code-input-<%= index + 1%>" id="copy-icon-<%= index + 1%>"></i></div>
        <input class="code-input" type="text" id="code-input-<%= index + 1%>" value="<%= command %>" spellcheck="false">
      </div>
    <% end %>
  </div>

  <div class="my-4 border-bottom"></div>


<!-- <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
<script>
  function flip() {
    $('.card-xml').toggleClass('back');
  }
</script> -->
<!-- <section class="xml-container"> -->
<!--   <div class="card-xml">
    <div class="front"> -->

  <p><strong>Your Schema</strong></p>

  <div id="openSchema" class="mb-3 ml-auto openSchema">
    <div class="d-flex justify-content-center">
      <p>Visualise your Schema</p>
      <%= image_tag "shut.png", class: "eyes-img eyes-on", id: "shut-eyes" %>
      <%= image_tag "hov-shut.png", class: "eyes-img eyes-hov-on", id: "shut-eyes" %>
      <%= image_tag "open.png", class: "eyes-img eyes-off imp_d_none", id: "open-eyes" %>
      <%= image_tag "hov-open.png", class: "eyes-img eyes-hov-off imp_d_none", id: "open-eyes" %>
    </div>
    <div class="iframe-wrapper" id="db-scheme-iframe-wrapper" style="display: none;">
      <iframe id="show-iframe"
          title="Schema Frame"
          width="100%"
          height="550"
          src="<%= "/sqldesigner/index.html" %>">
      </iframe>
    </div>
  </div>

  <p>Access your <strong>XML</strong> and update it.</p>
  <div class="code-block code-xmlfile d-flex">
  <div class="code-row">
    <div class="code-copy-icon"><i class="fas fa-copy" data-target="XML-input-command"></i></div>
      <%= simple_form_for @project, html: { class: "show-xml-form"} do |f| %>
        <%= f.text_area :xml_schema, id: "XML-input-command", class: "code-input", rows: "5", cols: "50", spellcheck: "false" %>
        <%= f.submit 'Update XML', class: "btn btn convert-now-button hvr-grow my-3" %>
      <% end %>
    </div>
  </div>

<!-- code to display schema builder -->


  <!-- <button id="openSchema" class="btn btn convert-now-button mb-3 ml-auto">Visual schema</button> -->






 <!--    </div> -->
<!--   </div> -->
<!--     <div class="back">
    </div> -->
<!-- </section> -->
<!-- <button onclick="flip()" class="purple-button-class-flip mt-3">flip the card</button>
 -->

  <div class="share-link-mobile">
    <div class="my-4 border-bottom"></div>
    <p><strong>Share this page</strong></p>
    <div class="link-code-block">
      <div class="code-row">
        <div class="code-copy-icon"><i class="fas fa-copy" data-target="code-input-link"></i></div>
        <input class="link-code-input" type="text" id="code-input-link" value="<%= request.original_url %>" spellcheck="false">
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Your app '<%= @project.name.gsub(/\s+/m, '_').downcase %>' will contain:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="font-family: Roboto, sans-serif;">
        <p>- JavaScript enabled</p>
        <p>- Webpacker</p>
        <p>- Yarn</p>
        <p>- Le wagon stylesheets</p>
        <p>- gem 'font-awesome'</p>
        <p>- gem 'simple form'</p>
        <p>- gem 'bootstrap'</p>
        <p>- gem 'devise'</p>
        <p>- gem 'jbuilder'</p>
        <p>- Reopsitory on your Github</p>
        <p>- Heroku deplyoment</p>
        <p>And much more!</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- old code to be saved in case -->
<!-- <span class="devise-for-span">Use devise for</span> -->
<!-- <div class="devise-dropdown"> -->

  <!-- <select class="form-control" id="devise-dropdown-select"> -->
    <%# @project.models.each do |model| %>
      <%# if model == "user" %>
        <!-- <option selected="selected" value="<%#= model %>"><%#= model %></option> -->
      <%# else %>
        <!-- <option value="<%#= model %>"><%#= model %></option> -->
      <%# end %>
    <%# end %>
  <!-- </select> -->

<!-- </div> -->